name: nexus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  provider: ^6.1.5+1
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  flutter_gemini: ^3.0.0
  flutter_svg: ^2.2.1
  flutter_gif: ^0.0.4
  iconsax: ^0.0.8
  url_launcher: ^6.3.2
  percent_indicator: ^4.2.5
  convex_bottom_bar: ^3.2.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^31.1.19
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_markdown: ^0.7.3
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.3.2
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  animate_do: ^4.2.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.10.2
  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.2
  youtube_player_iframe: ^5.2.2
  rive: ^0.14.2
  flutter_highlight: ^0.7.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/LoginSignUpAssets/
    - assets/imgs/
